# Generated by Django 5.0.6 on 2024-07-05 03:34

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):
    operations = [
        VectorExtension()
    ]
