# Generated by Django 5.2.1 on 2025-05-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0002_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='color_scheme',
            field=models.CharField(choices=[('aquillm_default_dark', 'Aquillm Default Dark'), ('aquillm_default_light', 'Aquillm Default Light'), ('aquillm_default_light_accessible_chat', 'Aquillm Default Light Accessible Chat'), ('aquillm_default_dark_accessible_chat', 'Aquillm Default Dark Accessible Chat'), ('high_contrast', 'High Contrast')], default='aquillm_default_dark', max_length=100),
        ),

        migrations.AlterField(
            model_name='usersettings',
            name='font_family',
            field=models.CharField(choices=[('latin_modern_roman', 'Latin Modern Roman'), ('sans_serif', 'Sans-serif'), ('verdana', 'Verdana'), ('timesnewroman', 'Times New Roman'), ('opendyslexic', 'OpenDyslexic'), ('lexend', 'Lexend'), ('comicsans', 'Comic Sans')], default='sans_serif', max_length=50),
        ),
    ]
