# Generated by Django 5.0.7 on 2024-09-17 23:14

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0002_pdfdocument_ingested_by_pdfdocument_ingestion_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='textchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_index', opclasses=['vector_l2_ops']),
        ),
    ]
