# Generated by Django 5.0.7 on 2024-07-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTextDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('full_text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='textchunk',
            name='chunk_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='full_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sttdocument',
            name='full_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='texdocument',
            name='full_text',
            field=models.TextField(),
        ),
    ]
