# Generated by Django 5.0.7 on 2024-07-12 01:09

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0003_rawtextdocument_textchunk_chunk_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
