# Generated by Django 5.0.7 on 2024-09-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0003_textchunk_chunk_embedding_index'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='textchunk',
            constraint=models.UniqueConstraint(fields=('doc_id', 'chunk_number'), name='uniqe_chunk_per_document'),
        ),
    ]
