# Generated by Django 5.0.7 on 2024-09-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0004_textchunk_uniqe_chunk_per_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textchunk',
            options={'ordering': ['doc_id', 'chunk_number']},
        ),
    ]
