# Generated by Django 5.0.7 on 2024-07-16 03:23

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0004_alter_textchunk_embedding'),
    ]

    operations = [
        TrigramExtension()
    ]
