# Generated by Django 5.0.7 on 2024-09-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0005_alter_textchunk_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfdocument',
            options={'ordering': ['-ingestion_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='rawtextdocument',
            options={'ordering': ['-ingestion_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='sttdocument',
            options={'ordering': ['-ingestion_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='texdocument',
            options={'ordering': ['-ingestion_date', 'title']},
        ),
    ]
