# Generated by Django 5.0.7 on 2024-07-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0005_pg_trgm_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='start_time',
            field=models.FloatField(null=True),
        ),
    ]
