# Generated by Django 5.0.7 on 2024-07-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0006_textchunk_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='texdocument',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
