# Generated by Django 5.0.7 on 2024-09-26 23:13

import aquillm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0006_alter_pdfdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconversation',
            name='tokens',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/', validators=[aquillm.models.validate_pdf_extension]),
        ),
    ]
