# Generated by Django 5.0.7 on 2024-10-23 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0007_llmconversation_tokens_alter_pdfdocument_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VTTDocument',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('full_text', models.TextField()),
                ('full_text_hash', models.CharField(db_index=True, max_length=64)),
                ('ingestion_date', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.FileField(null=True, upload_to='stt_audio/')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquillm.collection')),
                ('ingested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ingestion_date', 'title'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='STTDocument',
        ),
        migrations.AddConstraint(
            model_name='vttdocument',
            constraint=models.UniqueConstraint(fields=('collection', 'full_text_hash'), name='vttdocument_document_collection_unique'),
        ),
    ]
