# Generated by Django 5.0.7 on 2024-10-23 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0008_vttdocument_delete_sttdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='vttdocument',
            name='audio_file',
            field=models.FileField(null=True, upload_to='stt_audio/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'ogg', 'opus', 'm4a', 'aac'])]),
        ),
    ]
