# Generated by Django 5.0.7 on 2024-08-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0008_collection_collectionpermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='collections',
            field=models.ManyToManyField(to='aquillm.collection'),
        ),
        migrations.AddField(
            model_name='rawtextdocument',
            name='collections',
            field=models.ManyToManyField(to='aquillm.collection'),
        ),
        migrations.AddField(
            model_name='sttdocument',
            name='collections',
            field=models.ManyToManyField(to='aquillm.collection'),
        ),
        migrations.AddField(
            model_name='texdocument',
            name='collections',
            field=models.ManyToManyField(to='aquillm.collection'),
        ),
    ]
