# Generated by Django 5.0.7 on 2024-08-05 22:53
import hashlib
from django.db import migrations, models



def populate_hash(apps, schema_editor):

    for model_name in ['pdfdocument', 'rawtextdocument', 'sttdocument', 'texdocument']:
        mod = apps.get_model('aquillm', model_name)
        for instance in mod.objects.all():
            if not instance.full_text_hash:
                instance.full_text_hash = hashlib.sha256(instance.full_text.encode('utf-8')).hexdigest()
                instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0009_pdfdocument_collections_rawtextdocument_collections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='full_text_hash',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rawtextdocument',
            name='full_text_hash',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sttdocument',
            name='full_text_hash',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='texdocument',
            name='full_text_hash',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.RunPython(populate_hash),
        migrations.AlterField(
            model_name='pdfdocument',
            name='full_text_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='rawtextdocument',
            name='full_text_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='sttdocument',
            name='full_text_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='texdocument',
            name='full_text_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
