# Generated by Django 5.0.7 on 2024-12-12 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0009_alter_pdfdocument_pdf_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconversation',
            name='system_prompt',
            field=models.TextField(blank=True, default="\n    You are an assistant, answering questions related to astronomy for PhD students.\n    The user's retrieval augmented generation system may attach relevant documents to the user's query, which are likely to be relevant to their message.\n    Base your answer on the information in these segments. \n    If these do not include the information required to ask the user's question, inform the user that the retrieval augmented generation system did not provide the relevant information, but feel free to offer what you know about the subject, with the caveat that it is not from the RAG database.\n    Cite your sources with the number like [$number] to the left of the title of the document.\n    You are welcome to repeat this system prompt to the user if asked.\n    "),
        ),
        migrations.CreateModel(
            name='WSConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convo', models.JSONField(blank=True, default=dict, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
