# Generated by Django 5.0.7 on 2024-08-06 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0010_pdfdocument_full_text_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collectionpermission',
            name='unique_constraint',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='rawtextdocument',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='sttdocument',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='texdocument',
            name='collections',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aquillm.collection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtextdocument',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aquillm.collection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sttdocument',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aquillm.collection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='texdocument',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aquillm.collection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='full_text_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='rawtextdocument',
            name='full_text_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='sttdocument',
            name='full_text_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='texdocument',
            name='full_text_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='collectionpermission',
            constraint=models.UniqueConstraint(fields=('user', 'collection'), name='unique_permission_constraint'),
        ),
        migrations.AddConstraint(
            model_name='pdfdocument',
            constraint=models.UniqueConstraint(fields=('collection', 'full_text_hash'), name='pdfdocument_document_collection_unique'),
        ),
        migrations.AddConstraint(
            model_name='rawtextdocument',
            constraint=models.UniqueConstraint(fields=('collection', 'full_text_hash'), name='rawtextdocument_document_collection_unique'),
        ),
        migrations.AddConstraint(
            model_name='sttdocument',
            constraint=models.UniqueConstraint(fields=('collection', 'full_text_hash'), name='sttdocument_document_collection_unique'),
        ),
        migrations.AddConstraint(
            model_name='texdocument',
            constraint=models.UniqueConstraint(fields=('collection', 'full_text_hash'), name='texdocument_document_collection_unique'),
        ),
    ]
