# Generated by Django 5.0.7 on 2024-12-20 00:04

import aquillm.llm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0011_add_su'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsconversation',
            name='convo',
            field=models.JSONField(blank=True, default=aquillm.llm.Conversation.get_empty_conversation, null=True),
        ),
    ]
