# Generated by Django 5.0.7 on 2024-08-06 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0011_remove_collectionpermission_unique_constraint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='users',
            field=models.ManyToManyField(through='aquillm.CollectionPermission', to=settings.AUTH_USER_MODEL),
        ),
    ]
