# Generated by Django 5.1.4 on 2025-01-08 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0012_alter_wsconversation_convo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsconversation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 23, 48, 34, 779015, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wsconversation',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wsconversation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 23, 48, 40, 582895, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
