# Generated by Django 5.1.5 on 2025-01-30 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0013_wsconversation_created_at_wsconversation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='pdf_file',
            field=models.FileField(max_length=500, upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
