# Generated by Django 5.0.7 on 2024-08-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0013_llmconversation_llmconvomessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmconvomessage',
            options={'ordering': ['conversation', 'timestamp']},
        ),
    ]
