# Generated by Django 5.1.5 on 2025-01-23 20:57

from django.db import migrations
from aquillm.models import WSConversation

def add_rating_to_llm_message(apps, schema_editor):
    ws_convo = apps.get_model('aquillm', 'WSConversation')
    for wsconversation in ws_convo.objects.all():
        messages = wsconversation.convo['messages']
        for message in messages:
            message['rating'] = None
        wsconversation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0013_wsconversation_created_at_wsconversation_name_and_more'),
    ]

    operations = [
        migrations.RunPython(add_rating_to_llm_message)
    ]
