# Generated by Django 5.1.5 on 2025-01-22 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0013_wsconversation_created_at_wsconversation_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='aquillm.collection')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='aquillm.folder')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'parent', 'collection')},
            },
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_documents', to='aquillm.folder'),
        ),
        migrations.AddField(
            model_name='rawtextdocument',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_documents', to='aquillm.folder'),
        ),
        migrations.AddField(
            model_name='texdocument',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_documents', to='aquillm.folder'),
        ),
        migrations.AddField(
            model_name='vttdocument',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_documents', to='aquillm.folder'),
        ),
    ]
