# Generated by Django 5.1.5 on 2025-01-23 20:57
from uuid import uuid4
from django.db import migrations
from aquillm.models import WSConversation
from aquillm.llm import Conversation
from aquillm.models import WSConversation
from pydantic_core import to_jsonable_python

def add_rating_to_llm_message(apps, schema_editor):
    for wsconversation in WSConversation.objects.all():
        convo = wsconversation.convo_object
        for message in convo:
            message.rating = None
            message.message_uuid = uuid4()
        wsconversation.convo_object = convo
        wsconversation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0014_alter_pdfdocument_pdf_file'),
    ]

    operations = [
        migrations.RunPython(add_rating_to_llm_message)
    ]
