# Generated by Django 5.0.7 on 2024-08-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0014_alter_llmconvomessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmconversation',
            options={'ordering': ['updated_at']},
        ),
    ]
