# Generated by Django 5.1.5 on 2025-01-23 22:27

from django.db import migrations

from uuid import uuid4

def add_uuid_to_llm_message(apps, schema_editor):
    ws_convo = apps.get_model('aquillm', 'WSConversation')
    for wsconversation in ws_convo.objects.all():
        messages = wsconversation.convo['messages']
        for message in messages:
            message['message_uuid'] = str(uuid4())
        wsconversation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0014_add_rating_to_llm_message'),
    ]

    operations = [
        migrations.RunPython(add_uuid_to_llm_message)
    ]
