# Generated by Django 5.1.5 on 2025-01-29 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0014_folder_pdfdocument_folder_rawtextdocument_folder_and_more'),
        ('aquillm', '0015_add_uuid_to_llm_message'),
    ]

    operations = [
    ]
