# Generated by Django 5.1.6 on 2025-03-04 20:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0015_add_rating_to_llm_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandwrittenNotesDocument',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('full_text', models.TextField()),
                ('full_text_hash', models.CharField(db_index=True, max_length=64)),
                ('ingestion_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('image_file', models.ImageField(upload_to='handwritten_notes/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquillm.collection')),
                ('ingested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ingestion_date', 'title'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('collection', 'full_text_hash'), name='handwrittennotesdocument_document_collection_unique')],
            },
        ),
    ]
