# Generated by Django 5.1.5 on 2025-01-29 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0014_alter_pdfdocument_pdf_file'),
        ('aquillm', '0015_add_rating_to_llm_message'),
    ]

    operations = [
    ]
