# Generated by Django 5.0.7 on 2024-09-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0015_alter_llmconversation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconversation',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
