# Generated by Django 5.1.6 on 2025-02-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0015_add_rating_to_llm_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='ingestion_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawtextdocument',
            name='ingestion_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='texdocument',
            name='ingestion_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vttdocument',
            name='ingestion_complete',
            field=models.BooleanField(default=False),
        ),
    ]
