# Generated by Django 5.1.5 on 2025-02-04 01:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0016_merge_20250129_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='aquillm.collection'),
        ),
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documents', to='aquillm.collection'),
        ),
        migrations.AlterField(
            model_name='rawtextdocument',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documents', to='aquillm.collection'),
        ),
        migrations.AlterField(
            model_name='texdocument',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documents', to='aquillm.collection'),
        ),
        migrations.AlterField(
            model_name='vttdocument',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_documents', to='aquillm.collection'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'parent')},
        ),
    ]
 