# Generated by Django 5.1.6 on 2025-02-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0016_pdfdocument_ingestion_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmconvomessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='llmconvomessage',
            name='context_chunks',
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='ingestion_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rawtextdocument',
            name='ingestion_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='texdocument',
            name='ingestion_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vttdocument',
            name='ingestion_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='LLMConversation',
        ),
        migrations.DeleteModel(
            name='LLMConvoMessage',
        ),
    ]
