# Generated by Django 5.1.6 on 2025-02-28 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0018_alter_collection_options_collection_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textchunk',
            name='keywords',
        ),
    ]
