# Generated by Django 5.1.6 on 2025-03-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0019_remove_textchunk_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
