# Generated by Django 5.2 on 2025-04-13 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0020_emailwhitelist'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('color_scheme', models.CharField(choices=[('aquillm_default_dark', 'Aquillm Default Dark'), ('aquillm_default_light', 'Aquillm Default Light')], default='aquillm_default_dark', max_length=30)),
                ('font_family', models.CharField(choices=[('latin_modern_roman', 'Latin Modern Roman'), ('sans_serif', 'Sans-serif')], default='latin_modern_roman', max_length=50)),
            ],
        ),
    ]
