# Generated by Django 5.2 on 2025-04-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0020_emailwhitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtextdocument',
            name='source_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
