# Generated by Django 5.2 on 2025-05-03 03:22

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0020_emailwhitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoteroTextChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=50)),
                ('chunk_number', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['item_key', 'chunk_number'],
                'indexes': [models.Index(fields=['item_key'], name='aquillm_zot_item_ke_32d665_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='zotero_chunk_embedding_index', opclasses=['vector_l2_ops'])],
                'unique_together': {('item_key', 'chunk_number')},
            },
        ),
    ]
