FROM python:3.12-slim

# Set environment variables

ENV PORT=${PORT}
# Set working directory
WORKDIR /app

# Copy requirements first to leverage Docker cache
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN apt update && apt install -y curl
# Copy the rest of the application
COPY . .

# Set working directory for Django app
WORKDIR /app/aquillm

# Command to run the application
CMD pytest -s -v \
    --ds=aquillm.settings \
    --reuse-db \
    | tee ../test-results.txt