FROM python:3.12-slim

ENV PORT=${PORT}
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN apt update && apt install -y curl nodejs npm
COPY . .


WORKDIR /app/aquillm

# Command to run the application
CMD ["sh", "-c", "/app/deployment/run.sh"]
